# Makefile for the main HotDrink library.

include $(MAKEDIR)/Makefile.common
include $(MAKEDIR)/Makefile.js

##################################################
# mandatory configuration

TITLE := jsdoc

##################################################
# optional configuration

MAIN := $(TITLE).js
MAINPLUS := $(TITLE)-plus.js

SRCDIR := lib
SOURCES := \
  namespace.js \
  attach.js \
  source.js \
  context.js \
  main.js

HEADERS := \

OBJDIR := build

THIRD_PARTY_SOURCES := \

DOCDIR := doc

