# Makefile for the JSDoc application.

include $(MAKEDIR)/Makefile.common
include $(MAKEDIR)/Makefile.js

##################################################
# mandatory configuration

TITLE := jfdoc

##################################################
# optional configuration

ALL := app

SRCDIR := lib
SOURCES := \
  namespace.js \
  attach.js \
  source.js \
  tags/namespace.js \
  tags/file.js \
  documenter.js \
  parse.js \
  compile.js \
  main.js

HEADERS := \

OBJDIR := build

THIRD_PARTY_SOURCES := \

DOCDIR := doc


