# Makefile for the JFDoc library.

include $(MAKEDIR)/Makefile.common
include $(MAKEDIR)/Makefile.js

##################################################
# mandatory configuration

TITLE := jfdoc

##################################################
# optional configuration

SRCDIR := lib
SOURCES := \
  utility/lang.js \
  utility/esprima/treeIterator.js \
  utility/esprima/commentIterator.js \
  utility/handlebars.js \
  jfdoc.js \
  documenter.js \
  ast/name.js \
  ast/doclet.js \
  ast/file.js \
  ast/decl.js \
  ast/scope.js \
  ast/symtab.js \
  ast/scopedIterator.js \
  parser/parser.js \
  parser/source.js \
  parser/tag.js \
  parser/symbols.js \
  tags/tags.js \
  tags/general.js \
  tags/file.js \
  tags/namespace.js \
  tags/function.js \
  tags/param.js \
  tags/class.js \
  generator/generator.js \
  generator/address.js \
  generator/crumbs.js \
  generator/files.js \
  generator/namespace.js \
  generator/function.js \
  generator/class.js

HEADERS := \

